### ISSUE TITLE
It's posible to add icons on pseudo elements?

### ISSUE THREAD

**Issue by VadimCeretean** [nuxt-community/fontawesome-module#17]
I want to add icons like content to :before element, it's posible?

**Comment by pimlie** [comment]
Not that I know, you can use classes still by using fontawesome's dom api but not sure how you could get those into a pseudo element. If you need that you are probably looking for a webfont solution, while fontawesome switched to svg

But your question is probably more suited for stackoverflow or the fontawesome repositories, thanks.
