### ISSUE TITLE
Could not find one or more icon

### ISSUE THREAD

**Issue by Kazuto** [nuxt-community/fontawesome-module#18]
I've did everything the Readme told me to, but I can't get any icons to work if I try to import them in my nuxt.config.js, only when I import them directly in a component.

```
Could not find one or more icon(s) {
  prefix: 'fas',
  iconName: 'faGithub'
} {}
```

```
buildModules: [
    [
      '@nuxtjs/fontawesome',
      {
        component: 'fa',
      },
    ],
  ],
fontawesome: {
  icons: {
    brands: ['faGithub'],
  },
},
```

```
<fa icon="faGithub" />
```

**Comment by pimlie** [comment]
See: https://github.com/FortAwesome/vue-fontawesome#using-brand-icons

You need to use `<fa :icon="['fab', 'github']" />` instead. 

Also reading this could be helpful: https://github.com/FortAwesome/vue-fontawesome#why-so-explicit-the-iconfar-coffee-syntax :)

**Comment by Kazuto** [comment]
Ah I see. Thanks for the answer :)
