### ISSUE TITLE
Icons are fine in dev but huge in production build

### ISSUE THREAD

**Issue by jdanino** [nuxt-community/fontawesome-module#6]
I've been using your package for a while and everything was working fine. However, after updating last week the Icons turned huge (as in 640 x 562 px) when in production mode. when in development mode everything is fine. I cant figure out what is causing this.. any idea?

**Comment by pimlie** [comment]
Could you please check:
- the contents of `.nuxt/fontawesome.js` in your buildDir? Is there any strange content?
- inspect your icons with the developer console, are they svg's with an `fa-*` classes? Are those classes listed with rules in the Style rules tab of the dev console? If they arent listed in the style rules tab, then the css is just not loaded.
If you are using PurgeCSS, try to white list all fa-* classes

**Comment by jdanino** [comment]
The contents in the build dir seems fine but the classes are indeed missing in production. 
I'm not using purgecss but it seems like some webpack settings may have changed since I did an npm update ( nuxt updated from (2.0.0 to 2.11.0)  as I am also seeing some strange css behaviour with an element-ui component where the css is incorrect..  Any pointers as to where to look would be greatly appreciated!

**Comment by jdanino** [comment]
Thanks for the reply. Turns out I was running purgeCSS and it removed the styles since the last npm update.

**Comment by cvharris** [comment]
I ran into this issue as well but have been unable to disable purgeCSS, what did you do specifically to prevent purge from running?

Really, this is a purgeCSS issue, though I'm sure others run into this same thing

**Comment by subdavis** [comment]
@jdanino could you provide some more info about how you fixed this?  I'm getting the same issue: styles aren't making it into my production build, but my icons are still there.

I was able to hack a fix by putting this in my nuxtConfig, but it seems like this should either be mentioned in the docs or there should be an easier fix:

```
purgeCSS: {
    whitelistPatterns: [/-fa$/, /^fa-/],
  }
```

**Comment by jdanino** [comment]
I ended up adding whitelistPatterns: [/fa/], to my nuxtconfig just like you did and I agree this could/should be mentioned somewhere

> @jdanino could you provide some more info about how you fixed this? I'm getting the same issue: styles aren't making it into my production build, but my icons are still there.
> 
> I was able to hack a fix by putting this in my nuxtConfig, but it seems like this should either be mentioned in the docs or there should be an easier fix:
> 
> ```
> purgeCSS: {
>     whitelistPatterns: [/-fa$/, /^fa-/],
>   }
> ```

**Comment by pimlie** [comment]
@jdanino Feel free to submit a PR to add a section to the readme about using PurgeCSS :)

**Comment by rtuttlecoder** [comment]
this is happening to me for Tailwind v.3.x but am not using purgeCss at all -- thoughts?

**Comment by B3JKER** [comment]
I found another solution on nuxt v2, when you don't use PurgeCSS - you have to install 2 packages that is not mentioned:
https://www.npmjs.com/package/@fortawesome/vue-fontawesome  -  yarn add @fortawesome/vue-fontawesome@latest
https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core  -  yarn add @fortawesome/fontawesome-svg-core
That 100% worked for me.

**Comment by twisty** [comment]
Slight update to above... on nuxt v2, this worked for me:

```bash
yarn add @fortawesome/vue-fontawesome@2
yarn add @fortawesome/fontawesome-svg-core
```
