### ISSUE TITLE
Problem using fas icons

### ISSUE THREAD

**Issue by kawoki** [nuxt-community/fontawesome-module#8]
I have this html code

```html
<fa :icon="['fas', 'arrow-next']" />
```

nuxt.config.js
```js
...
fontawesome: {
   icons: {
      solid: [ ..., 'fasArrowNext']
   }
}
...
```
and I am having an error in console

./.nuxt/fontawesome.js 10:105-124"export 'fasArrowLeft' (imported as 'freeFasFasArrowLeft') was not found in '@fortawesome/free-solid-svg-icons'./.nuxt/fontawesome.js 10:83-103"export 'fasArrowRight' (imported as 'freeFasFasArrowRight') was not found in '@fortawesome/free-solid-svg-icons'

I've already added @fortawesome/free-solid-svg-icons. How do I fix this? Thanks in advance 😄

**Comment by kawoki** [comment]
I was able to solve it 😄

**Comment by pimlie** [comment]
Sorry for late reply.

I suppose you've added the icon with name `arrowNext` instead of `fasArrowNext` ?

**Comment by claide** [comment]
@kawoki how'd you solve this issue? I encountered the same thing using **fas font**. Already added the solid svg icons thing

```
fontawesome: {
    icons: {
      solid: ['checkCircle']
    }
},
```

> "export 'checkCircle' (imported as 'freeFasCheckCircle') was not found in '@fortawesome/free-solid-svg-icons'

**Comment by mc316** [comment]
I had the same issue, I used the wrong prefix when importing the icons, it should be `fa` not `fab` .
```
'@nuxtjs/fontawesome', {
      component: 'fa',
      suffix: true,
      icons: {
        solid: [
          'faEnvelope',
          'faLaptop',
        ],
        brands: [
            'faLinkedin',
            'faTwitter',
            'faFacebook',
        ],
```
